#pragma once

#include <inttypes.h>
#include <stdlib.h>
#include <stdbool.h>

#define SECTOR_SIZE_BYTES 512

#define FLOPPY_1440_NUMBER_OF_HEADS 2
#define FLOPPY_1440_NUMBER_OF_SECTORS 18
#define FLOPPY_1440_NUMBER_OF_CYLINDERS 80
#define FLOPPY_1440_SIZE_BYTES (FLOPPY_1440_NUMBER_OF_HEADS * FLOPPY_1440_NUMBER_OF_SECTORS * FLOPPY_1440_NUMBER_OF_CYLINDERS * SECTOR_SIZE_BYTES)

#define FLOPPY_720_SECTOR_SIZE_BYTES 512
#define FLOPPY_720_NUMBER_OF_HEADS 2
#define FLOPPY_720_NUMBER_OF_SECTORS 18
#define FLOPPY_720_NUMBER_OF_CYLINDERS 40
#define FLOPPY_720_SIZE_BYTES (FLOPPY_720_NUMBER_OF_HEADS * FLOPPY_720_NUMBER_OF_SECTORS * FLOPPY_720_NUMBER_OF_CYLINDERS * SECTOR_SIZE_BYTES)

#define FLOPPY_1200_SECTOR_SIZE_BYTES 512
#define FLOPPY_1200_NUMBER_OF_HEADS 2
#define FLOPPY_1200_NUMBER_OF_SECTORS 15
#define FLOPPY_1200_NUMBER_OF_CYLINDERS 80
#define FLOPPY_1200_SIZE_BYTES (FLOPPY_1200_NUMBER_OF_HEADS * FLOPPY_1200_NUMBER_OF_SECTORS * FLOPPY_1200_NUMBER_OF_CYLINDERS * SECTOR_SIZE_BYTES)

#define FLOPPY_360_SECTOR_SIZE_BYTES 512
#define FLOPPY_360_NUMBER_OF_HEADS 2
#define FLOPPY_360_NUMBER_OF_SECTORS 9
#define FLOPPY_360_NUMBER_OF_CYLINDERS 40
#define FLOPPY_360_SIZE_BYTES (FLOPPY_360_NUMBER_OF_HEADS * FLOPPY_360_NUMBER_OF_SECTORS * FLOPPY_360_NUMBER_OF_CYLINDERS * SECTOR_SIZE_BYTES)

#define HARD_NUMBER_OF_HEADS 16
#define HARD_NUMBER_OF_SECTORS 63
#define HARD_CYLINDER_SECTORS ((uint32_t)HARD_NUMBER_OF_HEADS * (uint32_t)HARD_NUMBER_OF_SECTORS)
#define HARD_CYLINDER_SIZE_BYTES ((uint32_t)SECTOR_SIZE_BYTES * HARD_CYLINDER_SECTORS)
#define MAX_HARD_NUMBER_OF_CYLINDERS 1024

enum DriveTypeFun8h {
    FUN8H_DRIVE_TYPE_FLOPPY_360 = 1,
    FUN8H_DRIVE_TYPE_FLOPPY_1200 = 2,
    FUN8H_DRIVE_TYPE_FLOPPY_720 = 3,
    FUN8H_DRIVE_TYPE_FLOPPY_1440 = 4
};

enum DriveTypeFun15h {
    FUN15H_DRIVE_TYPE_FLOPPY_DISK = 2,
    FUN15H_DRIVE_TYPE_HARD_DISK = 3
};

 struct __attribute__ ((packed)) DiskInfo {
    bool read_only;

    uint8_t drive_number;
    uint8_t drive_type_fun8h;
    uint8_t drive_type_fun15h;

    uint8_t number_of_heads;
    uint8_t number_of_sectors;
    uint16_t number_of_cylinders;

    uint32_t image_offset;
};

#define IMAGE_MAGIC_SIZE 4
#define IMAGE_MAGIC_STR "cool"

#define MAX_NUMBER_DISKS 32

#define MAX_NUMBER_FLOPPY_DRIVES 4
#define MAX_NUMBER_HARD_DRIVES 2

#define HARD_DRIVE_NUMBER_BASE 0x80
#define HARD_DRIVE_NUMBER_MASK 0x0f

struct __attribute__ ((packed)) ImageInfo {
    char magic[IMAGE_MAGIC_SIZE];

    struct DiskInfo dis[MAX_NUMBER_DISKS];
};

uint32_t size_blocks(struct DiskInfo* di);
bool has_geometry(const struct DiskInfo* di);
bool is_hard_drive(uint8_t drive_number);